services:
  controller:
    depends_on:
      db:
        condition: service_started
      valkey:
        condition: service_healthy
    image: ghcr.io/martina-ctf/ahaz:latest
    build:
      context: .
      dockerfile: ./Dockerfile.controller
    ports:
      - "5000:5000"
    volumes:
      - ./data/certs/:/certdir
      - ./data/kubectl:/.kube/
    environment:
      CERT_DIR_CONTAINER: "/certdir/"
      DB_IP: "db"
      DB_DBNAME: "ahaz"
      DB_USERNAME: "mongodb"
      DB_PASSWORD: "I_LOVE_NOSQL!!!"
      REDIS_URL: "redis://valkey:6379"
      PUBLIC_DOMAINNAME: "ahaz.lan"
      K8S_IP_RANGE: "10.42.0.0 255.255.255.0"
      K8S_IMAGEPULLSECRET_NAME: "regcred"
      K8S_IMAGEPULLSECRET_NAMESPACE: "default"
      TEAM_PORT_RANGE_START: 31000
      TEAM_BACKUP_PORT_RANGE_START: 30500
      TEAM_BACKUP_PORT_RANGE_END: 30999
      LOGLEVEL: "DEBUG"
      OVPN_IMAGE: "lisenet/openvpn"
      OVPN_TAG: "2.6.14"
    networks:
      internal:
      default:
  db: 
    image: mongo:8.3.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongodb"
      MONGO_INITDB_ROOT_PASSWORD: "I_LOVE_NOSQL!!!"
      MONGO_INITDB_DATABASE: "ahaz"
      GLIBC_TUNABLES: "glibc.pthread.rseq=1" # fixes a bug in mongo where it hates newer kernels, see https://jira.mongodb.org/browse/SERVER-121912
    volumes:
      - ./data/mongodb:/data/db
    networks:
      internal:
    # FIXME: Disable me in prod!
    ports:
      - "127.0.0.1:27017:27017" # keep it bound to loopback, in case the user forgets to disable; use SSH tunneling to access it on other machines
  valkey:
    image: valkey/valkey:9.1.0-alpine
    restart: always
    volumes:
      - ./data/valkey:/data
    healthcheck:
      test: ["CMD-SHELL", "valkey-cli ping | grep PONG"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 10s
      start_interval: 0.1s
    networks:
      internal:
networks:
  internal:
    driver: bridge
    internal: true
  default:
