services:
  controller:
    depends_on:
      db:
        condition: service_started
    image: ghcr.io/martina-ctf/ahaz:latest
    build:
      context: .
      dockerfile: ./Dockerfile.controller
    ports:
      - "5000:5000"
    volumes:
      - ./ahaz_data/certs/:/certdir
      - ./ahaz_data/kubectl:/.kube/
    environment:
      CERT_DIR_CONTAINER: "/certdir/"
      DB_IP: "db"
      DB_DBNAME: "ahaz"
      DB_USERNAME: "ahaz"
      DB_PASSWORD: "ahaz"
      REDIS_URL: "redis://redis:6379"
      PUBLIC_DOMAINNAME: "ahaz.lan"
      K8S_IP_RANGE: "10.42.0.0 255.255.255.0"
      K8S_IMAGEPULLSECRET_NAME: "regcred"
      K8S_IMAGEPULLSECRET_NAMESPACE: "default"
      TEAM_PORT_RANGE_START: 31000
      TEAM_BACKUP_PORT_RANGE_START: 30500
      TEAM_BACKUP_PORT_RANGE_END: 30999
      LOGLEVEL: "DEBUG"
      OVPN_IMAGE: "lisenet/openvpn"
      OVPN_TAG: "2.6.14"
    networks:
      internal:
      default:
  db:
    image: postgres:18.3-alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: "ahaz"
      # Note: For more complex environments, read: https://github.com/docker-library/docs/blob/master/postgres/README.md#docker-secrets
      POSTGRES_PASSWORD: "ahaz"
      POSTGRES_DB: "ahaz"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./ahaz_data/postgres/data:/var/lib/postgresql/data
      - ./ahaz_data/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      internal:
    # TODO: healthcheck
  redis:
    image: redis:4
    restart: always
    volumes:
      - ./ahaz_data/redis:/data
    networks:
      internal:
networks:
  internal:
    driver: bridge
    internal: true
  default:
